name: Run Meeting Analysis

# This allows you to run the workflow manually from the Actions tab
on:
  workflow_dispatch:
  # This runs the workflow automatically every hour
  schedule:
    - cron: '0 * * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install the libraries from your requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run your main.py script
      # This 'env' block securely passes your GitHub Secrets to the script
      - name: Execute analysis script
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py
